/** Every fixed user-facing string, by id (the C core's VS_<id>). */
export const STR = {
    TAG_RUNOUT: 'Runout',
    TAG_POSITIONING: 'Positioning',
    TAG_NOT_INSERTED: 'Not inserted',
    TAG_ERROR: 'Error',
    TAG_LOADING: 'Loading',
    TAG_UNLOADING: 'Unloading',
    TAG_CONFIRM: 'Confirm',
    TAGD_NOT_INSERTED: 'No spool is inserted.',
    TAGD_ERROR: 'This spool reported an error.',
    TAGD_RUNOUT: 'The spool ran out; the printer is switching to the next spare.',
    TAGD_POSITIONING: 'The spool is being positioned in the feeder.',
    TAGD_LOADING: 'This spool is loading into the toolhead.',
    TAGD_UNLOADING: 'This spool is unloading from the toolhead.',
    TAGD_CONFIRM: 'Confirm the linked Spoolman spool.',
    ALERT_DRYER: 'The dryer reported a fault.',
    ALERT_ADAPTER: "The dryer's power adapter is not connected.",
    UNKNOWN_MARK: '?',
    INFINITY_MARK: '∞',
    STATUS_LOADING: 'Loading filament',
    STATUS_UNLOADING: 'Unloading filament',
    STATUS_LOADED: 'Filament loaded',
    STATUS_NO_FILAMENT: 'No filament loaded',
    STATUS_RUNOUT: 'Filament ran out',
    UNIT_OFFLINE: 'Offline',
    LABEL_ALERTS: 'Alerts',
    LABEL_SETTINGS: 'Settings',
    LABEL_FAULT: 'Fault',
    LABEL_PRESSURE: 'Pressure',
    LABEL_NO_ALERTS: 'No alerts',
    LABEL_CLOSE: 'Close',
    LABEL_CANCEL: 'Cancel',
    LABEL_NO_RESPONSE: 'No response from the printer',
    ACTION_LOAD: 'Load',
    ACTION_UNLOAD: 'Unload',
    ACTION_STOP: 'Stop',
    ACTION_RETRY_LOAD: 'Retry',
    ACTION_RESUME: 'Resume',
    ACTION_CLEAR_FAULT: 'Clear fault',
    ACTION_CLEAR_ERRORS: 'Clear errors',
    ACTION_DRY_START: 'Start drying',
    ACTION_DRY_STOP: 'Stop drying',
    ACTION_ON: 'On',
    ACTION_OFF: 'Off',
    ACTION_ASSIGN_SPOOL: 'Assign spool',
    ACTION_REFRESH_SPOOLS: 'Refresh spools',
    ACTION_UNLINK: 'Unlink spool',
    ACTION_REREAD: 'Re-read tag',
    ACTION_CALIBRATE: 'Calibrate',
    REASON_POSITIONING: 'The spool is still being positioned',
    REASON_NOT_GROUPED: 'Assign this spool to a tool first',
    REASON_NO_HOST_ID: 'The printer has not seen this spool yet',
    REASON_NOTHING_BUSY: 'Nothing is loading or unloading',
    REASON_UNIT_UNKNOWN: 'The printer has not reported this unit yet',
    REASON_NO_TARGET: 'No target is set',
    REASON_LANE_UNKNOWN: "The printer has not reported this unit's lane yet",
    REASON_NO_FILAMENT: 'No filament is loaded',
    REASON_BAY_EMPTY: 'No spool is inserted',
    REASON_ALREADY_LOADED: 'This spool is already loaded',
    REASON_NOT_LOADED: 'This spool is not loaded',
    REASON_BUSY_HERE: 'The toolhead is busy with this spool',
    REASON_BAY_ERROR: 'This spool reported an error',
    REASON_NO_LINK: 'No Spoolman spool is linked',
    REASON_DRYER_IDLE: 'The dryer is not running',
    CONFIRM_UNLOAD_TITLE: 'Unload while printing?',
    CONFIRM_UNLOAD_TEXT: 'The print will pause while the toolhead unloads.',
    CONFIRM_UNLOAD_OK: 'Unload',
    CONFIRM_STOP_TITLE: 'Stop this load?',
    CONFIRM_STOP_TEXT: 'The load in progress will be canceled.',
    CONFIRM_STOP_OK: 'Stop',
    CONFIRM_CLEAR_FAULT_TITLE: 'Clear this fault?',
    CONFIRM_CLEAR_FAULT_TEXT: 'Only claim this once the problem is actually solved.',
    CONFIRM_CLEAR_FAULT_OK: 'Clear fault',
    CONFIRM_CLEAR_ERRORS_TITLE: 'Clear every error?',
    CONFIRM_CLEAR_ERRORS_TEXT: 'Only claim this once the problem is actually solved.',
    CONFIRM_CLEAR_ERRORS_OK: 'Clear errors',
    CONFIRM_CALIBRATE_TITLE: 'Calibrate this spool?',
    CONFIRM_CALIBRATE_TEXT: 'The filament moves while the PTFE length is measured.',
    CONFIRM_CALIBRATE_OK: 'Calibrate',
    ALERT_TITLE_STOP: 'Stop',
    ALERT_TITLE_PAUSE: 'Pause',
    ALERT_TITLE_INFO: 'Info',
    PANEL_NO_UNITS: 'No units connected',
    PANEL_NOT_READY: 'Waiting for the printer',
    PANEL_HOST_OFFLINE: 'Host offline',
    FIELD_TARGET_LABEL: 'Target',
    FIELD_HOURS_LABEL: 'Hours',
    FIELD_TARGET_UNIT: 'C',
    FIELD_HOURS_UNIT: 'h',
    FIELD_SPOOL_LABEL: 'Spool',
    DRYER_COOLING: 'Cooling',
    TOOLHEAD_DEFAULT_TITLE: 'Toolhead',
    SETTING_0_TITLE: 'Read filament on insertion',
    SETTING_0_NOTE: 'Read the spool tag when a spool is inserted (~20 s)',
    SETTING_1_TITLE: 'Read filament on startup',
    SETTING_1_NOTE: 'Read every spool tag at power-on (~1 min)',
    SETTING_2_TITLE: 'Reload from a spare on runout',
    SETTING_2_NOTE: 'Hand the lane to the next group member instead of pausing',
    SETTING_3_TITLE: 'Create Spoolman spools for new tags',
    SETTING_3_NOTE: 'Add an unknown tag to Spoolman on its first read',
    SETTING_4_TITLE: 'Apply pressure advance on load',
    SETTING_4_NOTE: "Push the spool's pressure advance to the printer on load",
} as const

export type StrId = keyof typeof STR

/** The host's five settings keys (C2 4.9), in the order of the settings rows. */
export const SETTING_KEYS = [
    'read_tag_on_insertion',
    'read_tags_at_startup',
    'auto_reload_on_runout',
    'auto_create_spoolman_spools',
    'apply_pa_on_load',
] as const
