/** English: the master table, with every id. */
export const STR_en = {
    TAG_RUNOUT: 'Runout',
    TAG_POSITIONING: 'Positioning',
    TAG_NOT_INSERTED: 'Not inserted',
    TAG_ERROR: 'Error',
    TAG_LOADING: 'Loading',
    TAG_UNLOADING: 'Unloading',
    TAG_CONFIRM: 'Confirm',
    TAGD_NOT_INSERTED: 'No spool is inserted.',
    TAGD_ERROR: 'This spool reported an error.',
    TAGD_RUNOUT: 'The spool ran out; the printer is switching to the next spare.',
    TAGD_POSITIONING: 'The spool is being positioned in the feeder.',
    TAGD_LOADING: 'This spool is loading into the toolhead.',
    TAGD_UNLOADING: 'This spool is unloading from the toolhead.',
    TAGD_CONFIRM: 'Confirm the linked Spoolman spool.',
    ALERT_DRYER: 'The dryer reported a fault.',
    ALERT_ADAPTER: "The dryer's power adapter is not connected.",
    UNKNOWN_MARK: '?',
    INFINITY_MARK: '∞',
    STATUS_LOADING: 'Loading filament',
    STATUS_UNLOADING: 'Unloading filament',
    STATUS_LOADED: 'Filament loaded',
    STATUS_NO_FILAMENT: 'No filament loaded',
    STATUS_RUNOUT: 'Filament ran out',
    STATUS_SPOOL_ERROR: 'reported an error',
    UNIT_OFFLINE: 'Offline',
    LABEL_ALERTS: 'Alerts',
    LABEL_SETTINGS: 'Settings',
    LABEL_FAULT: 'Fault',
    LABEL_PRESSURE: 'Pressure',
    LABEL_NO_ALERTS: 'No alerts',
    LABEL_CLOSE: 'Close',
    LABEL_CANCEL: 'Cancel',
    LABEL_NO_RESPONSE: 'No response from the printer',
    ACTION_LOAD: 'Load',
    ACTION_UNLOAD: 'Unload',
    ACTION_STOP: 'Stop',
    ACTION_RETRY_LOAD: 'Retry',
    ACTION_RESUME: 'Resume',
    ACTION_CLEAR_FAULT: 'Clear fault',
    ACTION_CLEAR_ERRORS: 'Clear errors',
    ACTION_DRY_START: 'Start drying',
    ACTION_DRY_STOP: 'Stop drying',
    ACTION_ON: 'On',
    ACTION_OFF: 'Off',
    ACTION_ASSIGN_SPOOL: 'Assign spool',
    ACTION_REFRESH_SPOOLS: 'Refresh spools',
    ACTION_UNLINK: 'Unlink spool',
    ACTION_REREAD: 'Re-read tag',
    ACTION_CALIBRATE: 'Calibrate',
    REASON_POSITIONING: 'The spool is still being positioned',
    REASON_NOT_GROUPED: 'Assign this spool to a tool first',
    REASON_NO_HOST_ID: 'The printer has not seen this spool yet',
    REASON_NOTHING_BUSY: 'Nothing is loading or unloading',
    REASON_UNIT_UNKNOWN: 'The printer has not reported this unit yet',
    REASON_NO_TARGET: 'No target is set',
    REASON_LANE_UNKNOWN: "The printer has not reported this unit's lane yet",
    REASON_NO_FILAMENT: 'No filament is loaded',
    REASON_BAY_EMPTY: 'No spool is inserted',
    REASON_ALREADY_LOADED: 'This spool is already loaded',
    REASON_NOT_LOADED: 'This spool is not loaded',
    REASON_BUSY_HERE: 'The toolhead is busy with this spool',
    REASON_BAY_ERROR: 'This spool reported an error',
    REASON_NO_LINK: 'No Spoolman spool is linked',
    REASON_DRYER_IDLE: 'The dryer is not running',
    CONFIRM_UNLOAD_TITLE: 'Unload while printing?',
    CONFIRM_UNLOAD_TEXT: 'The print will pause while the toolhead unloads.',
    CONFIRM_UNLOAD_OK: 'Unload',
    CONFIRM_STOP_TITLE: 'Stop this load?',
    CONFIRM_STOP_TEXT: 'The load in progress will be canceled.',
    CONFIRM_STOP_OK: 'Stop',
    CONFIRM_CLEAR_FAULT_TITLE: 'Clear this fault?',
    CONFIRM_CLEAR_FAULT_TEXT: 'Only claim this once the problem is actually solved.',
    CONFIRM_CLEAR_FAULT_OK: 'Clear fault',
    CONFIRM_CLEAR_ERRORS_TITLE: 'Clear every error?',
    CONFIRM_CLEAR_ERRORS_TEXT: 'Only claim this once the problem is actually solved.',
    CONFIRM_CLEAR_ERRORS_OK: 'Clear errors',
    CONFIRM_CALIBRATE_TITLE: 'Calibrate this spool?',
    CONFIRM_CALIBRATE_TEXT: 'The filament moves while the PTFE length is measured.',
    CONFIRM_CALIBRATE_OK: 'Calibrate',
    ALERT_TITLE_STOP: 'Stop',
    ALERT_TITLE_PAUSE: 'Pause',
    ALERT_TITLE_INFO: 'Info',
    PANEL_NO_UNITS: 'No units connected',
    PANEL_NOT_READY: 'Waiting for the printer',
    PANEL_HOST_OFFLINE: 'Host offline',
    FIELD_TARGET_LABEL: 'Target',
    FIELD_HOURS_LABEL: 'Hours',
    FIELD_TARGET_UNIT: 'C',
    FIELD_HOURS_UNIT: 'h',
    FIELD_SPOOL_LABEL: 'Spool',
    DRYER_COOLING: 'Cooling',
    TOOLHEAD_DEFAULT_TITLE: 'Toolhead',
    SETTING_0_TITLE: 'Read filament on insertion',
    SETTING_0_NOTE: 'Read the spool tag when a spool is inserted (~20 s)',
    SETTING_1_TITLE: 'Read filament on startup',
    SETTING_1_NOTE: 'Read every spool tag at power-on (~1 min)',
    SETTING_2_TITLE: 'Reload from a spare on runout',
    SETTING_2_NOTE: 'Hand the lane to the next group member instead of pausing',
    SETTING_3_TITLE: 'Create Spoolman spools for new tags',
    SETTING_3_NOTE: 'Add an unknown tag to Spoolman on its first read',
    SETTING_4_TITLE: 'Apply pressure advance on load',
    SETTING_4_NOTE: "Push the spool's pressure advance to the printer on load",
    SETTING_5_TITLE: 'Language',
    SETTING_5_NOTE: 'The language of this panel and of the display',
} as const

export type StrId = keyof typeof STR_en

/** qps: only the ids it translates; the rest fall back to English. */
export const STR_qps: Partial<Record<StrId, string>> = {
    TAG_RUNOUT: '[Ŕúñôúť……]',
    TAG_POSITIONING: '[Ƥôšíťíôñíñğ…………]',
    TAG_NOT_INSERTED: '[Ñôť íñšéŕťéď…………]',
    TAG_ERROR: '[Éŕŕôŕ……]',
    TAG_LOADING: '[Ĺôáďíñğ……]',
    TAG_UNLOADING: '[Úñļôáďíñğ………]',
    TAG_CONFIRM: '[Çôñƒíŕɱ……]',
    TAGD_NOT_INSERTED: '[Ñô šƥôôļ íš íñšéŕťéď.……………………]',
    TAGD_ERROR: '[Ťĥíš šƥôôļ ŕéƥôŕťéď áñ éŕŕôŕ.……………………………]',
    TAGD_RUNOUT: '[Ťĥé šƥôôļ ŕáñ ôúť; ťĥé ƥŕíñťéŕ íš šŵíťçĥíñğ ťô ťĥé ñéẋť šƥáŕé.………………………………………………………………]',
    TAGD_POSITIONING: '[Ťĥé šƥôôļ íš ƀéíñğ ƥôšíťíôñéď íñ ťĥé ƒééďéŕ.……………………………………………]',
    TAGD_LOADING: '[Ťĥíš šƥôôļ íš ļôáďíñğ íñťô ťĥé ťôôļĥéáď.…………………………………………]',
    TAGD_UNLOADING: '[Ťĥíš šƥôôļ íš úñļôáďíñğ ƒŕôɱ ťĥé ťôôļĥéáď.…………………………………………]',
    TAGD_CONFIRM: '[Çôñƒíŕɱ ťĥé ļíñķéď Šƥôôļɱáñ šƥôôļ.…………………………………]',
    ALERT_DRYER: '[Ťĥé ďŕýéŕ ŕéƥôŕťéď á ƒáúļť.…………………………]',
    ALERT_ADAPTER: "[Ťĥé ďŕýéŕ'š ƥôŵéŕ áďáƥťéŕ íš ñôť çôññéçťéď.……………………………………………]",
    STATUS_LOADING: '[Ĺôáďíñğ ƒíļáɱéñť………………]',
    STATUS_UNLOADING: '[Úñļôáďíñğ ƒíļáɱéñť…………………]',
    STATUS_LOADED: '[Ƒíļáɱéñť ļôáďéď………………]',
    STATUS_NO_FILAMENT: '[Ñô ƒíļáɱéñť ļôáďéď…………………]',
    STATUS_RUNOUT: '[Ƒíļáɱéñť ŕáñ ôúť………………]',
    STATUS_SPOOL_ERROR: '[ŕéƥôŕťéď áñ éŕŕôŕ………………]',
    UNIT_OFFLINE: '[Ôƒƒļíñé……]',
    LABEL_ALERTS: '[Áļéŕťš……]',
    LABEL_SETTINGS: '[Šéťťíñğš………]',
    LABEL_FAULT: '[Ƒáúļť……]',
    LABEL_PRESSURE: '[Ƥŕéššúŕé………]',
    LABEL_NO_ALERTS: '[Ñô áļéŕťš………]',
    LABEL_CLOSE: '[Çļôšé……]',
    LABEL_CANCEL: '[Çáñçéļ……]',
    LABEL_NO_RESPONSE: '[Ñô ŕéšƥôñšé ƒŕôɱ ťĥé ƥŕíñťéŕ……………………………]',
    ACTION_LOAD: '[Ĺôáď……]',
    ACTION_UNLOAD: '[Úñļôáď……]',
    ACTION_STOP: '[Šťôƥ……]',
    ACTION_RETRY_LOAD: '[Ŕéťŕý……]',
    ACTION_RESUME: '[Ŕéšúɱé……]',
    ACTION_CLEAR_FAULT: '[Çļéáŕ ƒáúļť…………]',
    ACTION_CLEAR_ERRORS: '[Çļéáŕ éŕŕôŕš…………]',
    ACTION_DRY_START: '[Šťáŕť ďŕýíñğ…………]',
    ACTION_DRY_STOP: '[Šťôƥ ďŕýíñğ…………]',
    ACTION_ON: '[Ôñ……]',
    ACTION_OFF: '[Ôƒƒ……]',
    ACTION_ASSIGN_SPOOL: '[Áššíğñ šƥôôļ…………]',
    ACTION_REFRESH_SPOOLS: '[Ŕéƒŕéšĥ šƥôôļš……………]',
    ACTION_UNLINK: '[Úñļíñķ šƥôôļ…………]',
    ACTION_REREAD: '[Ŕé-ŕéáď ťáğ…………]',
    ACTION_CALIBRATE: '[Çáļíƀŕáťé………]',
    REASON_POSITIONING: '[Ťĥé šƥôôļ íš šťíļļ ƀéíñğ ƥôšíťíôñéď……………………………………]',
    REASON_NOT_GROUPED: '[Áššíğñ ťĥíš šƥôôļ ťô á ťôôļ ƒíŕšť…………………………………]',
    REASON_NO_HOST_ID: '[Ťĥé ƥŕíñťéŕ ĥáš ñôť šééñ ťĥíš šƥôôļ ýéť………………………………………]',
    REASON_NOTHING_BUSY: '[Ñôťĥíñğ íš ļôáďíñğ ôŕ úñļôáďíñğ………………………………]',
    REASON_UNIT_UNKNOWN: '[Ťĥé ƥŕíñťéŕ ĥáš ñôť ŕéƥôŕťéď ťĥíš úñíť ýéť…………………………………………]',
    REASON_NO_TARGET: '[Ñô ťáŕğéť íš šéť………………]',
    REASON_LANE_UNKNOWN: "[Ťĥé ƥŕíñťéŕ ĥáš ñôť ŕéƥôŕťéď ťĥíš úñíť'š ļáñé ýéť…………………………………………………]",
    REASON_NO_FILAMENT: '[Ñô ƒíļáɱéñť íš ļôáďéď……………………]',
    REASON_BAY_EMPTY: '[Ñô šƥôôļ íš íñšéŕťéď……………………]',
    REASON_ALREADY_LOADED: '[Ťĥíš šƥôôļ íš áļŕéáďý ļôáďéď……………………………]',
    REASON_NOT_LOADED: '[Ťĥíš šƥôôļ íš ñôť ļôáďéď………………………]',
    REASON_BUSY_HERE: '[Ťĥé ťôôļĥéáď íš ƀúšý ŵíťĥ ťĥíš šƥôôļ……………………………………]',
    REASON_BAY_ERROR: '[Ťĥíš šƥôôļ ŕéƥôŕťéď áñ éŕŕôŕ……………………………]',
    REASON_NO_LINK: '[Ñô Šƥôôļɱáñ šƥôôļ íš ļíñķéď…………………………]',
    REASON_DRYER_IDLE: '[Ťĥé ďŕýéŕ íš ñôť ŕúññíñğ………………………]',
    CONFIRM_UNLOAD_TITLE: '[Úñļôáď ŵĥíļé ƥŕíñťíñğ?……………………]',
    CONFIRM_UNLOAD_TEXT: '[Ťĥé ƥŕíñť ŵíļļ ƥáúšé ŵĥíļé ťĥé ťôôļĥéáď úñļôáďš.…………………………………………………]',
    CONFIRM_UNLOAD_OK: '[Úñļôáď……]',
    CONFIRM_STOP_TITLE: '[Šťôƥ ťĥíš ļôáď?………………]',
    CONFIRM_STOP_TEXT: '[Ťĥé ļôáď íñ ƥŕôğŕéšš ŵíļļ ƀé çáñçéļéď.………………………………………]',
    CONFIRM_STOP_OK: '[Šťôƥ……]',
    CONFIRM_CLEAR_FAULT_TITLE: '[Çļéáŕ ťĥíš ƒáúļť?………………]',
    CONFIRM_CLEAR_FAULT_TEXT: '[Ôñļý çļáíɱ ťĥíš ôñçé ťĥé ƥŕôƀļéɱ íš áçťúáļļý šôļṽéď.……………………………………………………]',
    CONFIRM_CLEAR_FAULT_OK: '[Çļéáŕ ƒáúļť…………]',
    CONFIRM_CLEAR_ERRORS_TITLE: '[Çļéáŕ éṽéŕý éŕŕôŕ?…………………]',
    CONFIRM_CLEAR_ERRORS_TEXT: '[Ôñļý çļáíɱ ťĥíš ôñçé ťĥé ƥŕôƀļéɱ íš áçťúáļļý šôļṽéď.……………………………………………………]',
    CONFIRM_CLEAR_ERRORS_OK: '[Çļéáŕ éŕŕôŕš…………]',
    CONFIRM_CALIBRATE_TITLE: '[Çáļíƀŕáťé ťĥíš šƥôôļ?……………………]',
    CONFIRM_CALIBRATE_TEXT: '[Ťĥé ƒíļáɱéñť ɱôṽéš ŵĥíļé ťĥé ƤŤƑÉ ļéñğťĥ íš ɱéášúŕéď.………………………………………………………]',
    CONFIRM_CALIBRATE_OK: '[Çáļíƀŕáťé………]',
    ALERT_TITLE_STOP: '[Šťôƥ……]',
    ALERT_TITLE_PAUSE: '[Ƥáúšé……]',
    ALERT_TITLE_INFO: '[Íñƒô……]',
    PANEL_NO_UNITS: '[Ñô úñíťš çôññéçťéď…………………]',
    PANEL_NOT_READY: '[Ŵáíťíñğ ƒôŕ ťĥé ƥŕíñťéŕ………………………]',
    PANEL_HOST_OFFLINE: '[Ĥôšť ôƒƒļíñé…………]',
    FIELD_TARGET_LABEL: '[Ťáŕğéť……]',
    FIELD_HOURS_LABEL: '[Ĥôúŕš……]',
    FIELD_TARGET_UNIT: '[Ç……]',
    FIELD_HOURS_UNIT: '[ĥ……]',
    FIELD_SPOOL_LABEL: '[Šƥôôļ……]',
    DRYER_COOLING: '[Çôôļíñğ……]',
    TOOLHEAD_DEFAULT_TITLE: '[Ťôôļĥéáď………]',
    SETTING_0_TITLE: '[Ŕéáď ƒíļáɱéñť ôñ íñšéŕťíôñ…………………………]',
    SETTING_0_NOTE: '[Ŕéáď ťĥé šƥôôļ ťáğ ŵĥéñ á šƥôôļ íš íñšéŕťéď (~20 š)……………………………………………………]',
    SETTING_1_TITLE: '[Ŕéáď ƒíļáɱéñť ôñ šťáŕťúƥ………………………]',
    SETTING_1_NOTE: '[Ŕéáď éṽéŕý šƥôôļ ťáğ áť ƥôŵéŕ-ôñ (~1 ɱíñ)…………………………………………]',
    SETTING_2_TITLE: '[Ŕéļôáď ƒŕôɱ á šƥáŕé ôñ ŕúñôúť……………………………]',
    SETTING_2_NOTE: '[Ĥáñď ťĥé ļáñé ťô ťĥé ñéẋť ğŕôúƥ ɱéɱƀéŕ íñšťéáď ôƒ ƥáúšíñğ…………………………………………………………]',
    SETTING_3_TITLE: '[Çŕéáťé Šƥôôļɱáñ šƥôôļš ƒôŕ ñéŵ ťáğš……………………………………]',
    SETTING_3_NOTE: '[Áďď áñ úñķñôŵñ ťáğ ťô Šƥôôļɱáñ ôñ íťš ƒíŕšť ŕéáď…………………………………………………]',
    SETTING_4_TITLE: '[Áƥƥļý ƥŕéššúŕé áďṽáñçé ôñ ļôáď………………………………]',
    SETTING_4_NOTE: "[Ƥúšĥ ťĥé šƥôôļ'š ƥŕéššúŕé áďṽáñçé ťô ťĥé ƥŕíñťéŕ ôñ ļôáď…………………………………………………………]",
    SETTING_5_TITLE: '[Ĺáñğúáğé………]',
    SETTING_5_NOTE: '[Ťĥé ļáñğúáğé ôƒ ťĥíš ƥáñéļ áñď ôƒ ťĥé ďíšƥļáý………………………………………………]',
}

/** Every language table, keyed by code, English first. */
export const TABLES: Record<string, Partial<Record<StrId, string>>> = {
    en: STR_en,
    qps: STR_qps,
}

/** The language codes, in table order. */
export const LANG_CODES = ['en', 'qps'] as const

/** Each language by its own name, in the same order. */
export const LANG_NAMES = ['English', 'Pseudo-locale'] as const

/** The host's setting keys, in the order of the settings rows. */
export const SETTING_KEYS = [
    'read_tag_on_insertion',
    'read_tags_at_startup',
    'auto_reload_on_runout',
    'auto_create_spoolman_spools',
    'apply_pa_on_load',
    'language',
] as const
